"""initial migration

Revision ID: af780787145c
Revises: 
Create Date: 2024-09-19 14:03:48.724156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af780787145c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_noticias_infopress_raw_id', table_name='noticias_infopress_raw')
    op.drop_table('noticias_infopress_raw')
    op.drop_index('ix_noticias_expresso_das_ilhas_raw_id', table_name='noticias_expresso_das_ilhas_raw')
    op.drop_table('noticias_expresso_das_ilhas_raw')
    op.drop_index('ix_noticias_a_nacao_raw_id', table_name='noticias_a_nacao_raw')
    op.drop_table('noticias_a_nacao_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias_a_nacao_raw',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_of_news', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('news_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scrappe_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='noticias_a_nacao_raw_pkey')
    )
    op.create_index('ix_noticias_a_nacao_raw_id', 'noticias_a_nacao_raw', ['id'], unique=False)
    op.create_table('noticias_expresso_das_ilhas_raw',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_of_news', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('news_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scrappe_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='noticias_expresso_das_ilhas_raw_pkey')
    )
    op.create_index('ix_noticias_expresso_das_ilhas_raw_id', 'noticias_expresso_das_ilhas_raw', ['id'], unique=False)
    op.create_table('noticias_infopress_raw',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_of_news', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('news_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scrappe_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='noticias_infopress_raw_pkey')
    )
    op.create_index('ix_noticias_infopress_raw_id', 'noticias_infopress_raw', ['id'], unique=False)
    # ### end Alembic commands ###
